[package]
name = "series"
version = "0.2.0"
authors = ["Andreas Maier <andreas.martin.maier@desy.de>"]
description = "Laurent series in a single variable"
license = "GPL-3.0-or-later"
readme = "Readme.md"
keywords = ["math", "algebra"]
categories = ["science"]
repository = "https://github.com/a-maier/series-rust"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
